from anton.modules import learndb
from anton.modules import thanks
from anton.modules import urban_dictionary
from anton.modules import google
from anton.modules import zalgo
from anton.modules import slogan
from anton.modules import title_fetcher
from anton.modules import jenkins
from anton.modules import huzzah
from anton.modules import tickets
from anton.modules import debug
